# Generated by Django 4.0.4 on 2022-05-17 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRegister',
        ),
    ]
