# Generated by Django 4.0.4 on 2022-05-04 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacore', '0002_post_caption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reel', models.FileField(upload_to='')),
                ('caption', models.CharField(max_length=254, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
