# Generated by Django 4.0.4 on 2022-05-09 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instacore', '0010_like_remove_likes_user_remove_post_likes_post_liked_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='users',
        ),
    ]
