# Generated by Django 4.0.4 on 2022-05-09 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instacore', '0011_rename_user_profile_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='liked',
            new_name='likes',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
    ]
