# Generated by Django 4.0.4 on 2022-05-10 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instacore', '0013_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
    ]
