# Generated by Django 4.0.4 on 2022-05-15 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instacore', '0017_alter_post_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='users',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
    ]
