# Generated by Django 4.0.4 on 2022-05-16 10:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('instacore', '0018_rename_users_profile_user_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='likes',
            field=models.ManyToManyField(blank=True, default=None, to=settings.AUTH_USER_MODEL),
        ),
    ]
