# Generated by Django 4.0.4 on 2022-05-16 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacore', '0019_reel_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reel',
            name='likes',
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
