# Generated by Django 4.0.4 on 2022-05-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacore', '0020_remove_reel_likes_alter_profile_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(upload_to='profile pics'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='reel',
            field=models.FileField(upload_to='reels'),
        ),
    ]
