# Generated by Django 4.0.4 on 2022-05-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instacore', '0021_alter_post_image_alter_profile_photo_alter_reel_reel'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='name',
            field=models.CharField(blank=True, max_length=254),
        ),
    ]
