# Generated by Django 4.0.4 on 2022-05-17 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instacore', '0022_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo',
        ),
    ]
